DELETE FROM Media;
INSERT INTO Media (img_url,alt_txt) VALUES ("https://pbs.twimg.com/media/DMvdd6gWkAAehPL.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvfNuCXUAAW4F1.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvE0hsXUAAs4pl.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvXMmRU8AACFWi.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvQbNAXcAAyTI8.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMviSSOVoAAZyy5.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMr4y9nXkAAWbB4.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvWP1PWsAA6lPP.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DE6JC4AU0AEFE6k.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvdFlhW0AA4x-S.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMr2cTxVQAAneAm.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvVQk5W4AAI5Ss.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMve8MtX0AEzX87.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvm75YWAAAsCDL.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMu6hT2WAAAjIdq.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvW43jUIAAwsar.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMnrbtNU8AEC6lY.jpg","Image related to 'kitten' scraped from Twitter"),
("https://pbs.twimg.com/media/DMvfUrrXUAEsGqa.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMveH-OWsAAPLP1.jpg","Image related to 'cat' scraped from Twitter"),
("https://pbs.twimg.com/media/DMrz1zmVwAAzIGR.jpg","Image related to 'kitten' scraped from Twitter");
